services:
  mongodb:
    image: mongo
    container_name: bank-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=bank
    volumes:
      - ./.docker/mongodb:/data/db
    restart: always
    command: ["--replSet", "rs0", "--bind_ip_all"]

  redis:
    image: redis
    container_name: bank-redis
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/redis:/data
    restart: always
